use_frameworks!

target 'HuoghLibrary_Example' do
  pod 'HuoghLibrary', :path => '../'

  target 'HuoghLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
